# Generated by Django 5.0.1 on 2024-01-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('buyGeography', models.CharField(default='NO', max_length=100)),
                ('buyGeology', models.CharField(default='NO', max_length=100)),
            ],
        ),
    ]
